blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^historia/', include('historia.urls', namespace='historia')),
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),

]

historia/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.historia, name='historia'),

]

core/models.py
# -*- coding: utf 8 -*-
from django.db import models
from django.utils import timezone
from cloudinary.models import CloudinaryField

class Post(models.Model):
	titulo = models.CharField(max_length=100)
	texto = models.TextField(max_length=400, null=False,blank=False)


	def publish(self):
		self.save()

	def __str__(self):
		return self.titulo

class Postagem(models.Model):
	titulo2 = models.CharField(max_length=100)
	texto2 = models.TextField(max_length=400, null=False, blank=False)

	def publish(self):
		self.save()

	def __str__(self):
		return self.titulo2

historia/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.utils import timezone

def index(request):
	return render(request, 'core/index.html', {})

historia/views.py
from django.shortcuts import render
from django.utils import timezone
#from core.models import Postagem
from core.models import Post

#acima estou importanto as classes do models.py
def historia(request):
	posts = Post.objects.all()
	return render(request, 'historia/historia.html', {'posts': posts})

core/templates/core/index.html
{% load staticfiles%}
<html>
	<head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'css/pet.css' %}">
	</head>
	<div class="timbre">
		<header class='cabeca'><img src="{% static 'image/timbre1.jpg' %}" alt="noob"></header>
	</div>
	<body>
		<div class="tabela">
			<table border="2">
		    <tr>
		        <button class="btn1" ><a href="{% url 'historia:historia' %}">Historia</a></button><button class="btn2">Seu pet mania</button><button class="btn3">Nosso Cartoon</button><button class="btn4">Nos envie seu pet</button><button class="btn5">Pedigree</button><button class="btn6">Contate-nos</button>
		    </tr>
			</table>
		</div>
	</body>
</html>

historia/templates/historia/historia.html
{% load staticfiles%}
<html>
	<head>
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'css/pet.css' %}">
	</head>
	<div class="timbre">
		<header class='cabeca'><img src="{% static 'image/timbre1.jpg' %}" alt="noob"></header>
	</div>
	<body>
		<div class="tabela">
			<table border="2">
		    <tr>
		        <button class="btn1">História</button><button class="btn2">Seu pet mania</button><button class="btn3">Nosso Cartoon</button><button class="btn4">Nos envie seu pet</button><button class="btn5">Pedigree</button><button class="btn6">Contate-nos</button>
		    </tr>
			</table>
		</div>
		<div class="postagem">
			{% for postagem in posts %}
				{{ postagem.titulo }}
				{{ postagem.texto }} 
			{% endfor %}
		</div>
	</body>
</html>